import 'package:flutter/services.dart' show rootBundle;
import 'recipe_model.dart'; // Import the file generated by Python

class RandomForestService {
  List<String> _vocab = [];
  bool _isLoaded = false;

  Future<void> loadVocab() async {
    String data = await rootBundle.loadString('assets/vocab.txt');
    _vocab = data.split('\n');
    _isLoaded = true;
  }

  /// Returns the name of the predicted recipe
  String predict(List<String> userIngredients) {
    if (!_isLoaded) return "Model not loaded";

    // 1. Convert User Ingredients to Vector (List of Doubles)
    // The model expects a list of 0.0 and 1.0, exactly the size of the vocab
    List<double> inputVector = List.filled(_vocab.length, 0.0);

    for (var ingredient in userIngredients) {
      // Find where this ingredient is in our vocab list
      int index = _vocab.indexOf(ingredient.toLowerCase().trim());
      if (index != -1) {
        inputVector[index] = 1.0;
      }
    }

    // 2. Call the generated 'score' function from recipe_model.dart
    // The m2cgen library generates a function called 'score(input)'
    // It returns a Map of { "Recipe Name": probability }
    var output = score(inputVector); 

    // 3. Find the recipe with the highest probability
    String bestRecipe = "";
    double highestProb = -1.0;

    // The output is likely a Map<String, double> or List depending on m2cgen version
    // Usually it returns a Map for classifiers.
    if (output is Map) {
      (output as Map).forEach((k, v) {
        if (v is num && v > highestProb) {
          highestProb = v.toDouble();
          bestRecipe = k.toString();
        }
      });
    }

    return bestRecipe;
  }
}