/// Auto-generated. Do NOT edit manually.
const List<String> recipeLabels = [
  'A Bit Different Breakfast Pizza',
  'Add In Anything Muffins',
  'All In The Kitchen Chili',
  'Almost Boston Market Creamed Spinach',
  'Almost Dairy Queen Blizzard Ice Cream Cake',
  'Almost Outback Steakhouse Shrimp Sauce',
  'Almost Starbucks Frappuccino',
  'Alouette Potatoes',
  'Amerikaner German Vanilla Biscuit',
  'Amigos Crisp Chicken Burritos',
  'Amish Cake Frosting Icing',
  'Amish Tomato Ketchup For Canning',
  'Ant Kelly S London Broil Marinade',
  'Any Muffins',
  'Any Type Nut Butter',
  'Anything Goes Low Fat Mushroom Sauce',
  'Apple A Day Milk Shake',
  'Apple Pie',
  'Ara S Potato Oup',
  'Arriba Baked Winter Squash Mexican Style',
  'Artichoke Hearts',
  'Asian Noodle Salad',
  'Atkins Friendly Cheesecake',
  'Aunt Johnnie S Pound Cake',
  'Aww Marinated Olives',
  'Aww Shucks Crescent Dough Dessert',
  'Backyard Style Barbecued Ribs',
  'Bacon Cheeseburger And Fries Soup',
  'Bailey S Hot Fudge Sauce',
  'Bake In Oozy Bread',
  'Baked Apple Cinnamon Oatmeal',
  'Bananas Foster Oatmeal',
  'Bananas Ice Cream Pie',
  'Bar Cheese',
  'Basic Beet Borscht',
  'Bbq Pork',
  'Beat The Blues Blue Cheese Risotto',
  'Beat This Banana Bread',
  'Beefy Seitan Log',
  'Berinzila Eggplant And Ham',
  'Berry French Toast Oatmeal',
  'Berry Good French Toast Bake',
  'Berry Good Smoothie',
  'Better Than A Baked Potato Soup',
  'Better Than A Can Homemade Sloppy Joes',
  'Better Than Bouillon Gravy',
  'Better Than Cinnabon Cinnamon Rolls',
  'Better Than Crack Brownies',
  'Better Than Sex Strawberries',
  'Better Than Spaghetti Squash Bake',
  'Better Than Tofu Cheesecake',
  'Better Then Bush S Baked Beans',
  'Big Easy Gumbo',
  'Big Mac Meatloaf',
  'Biggest Loser Fish Tacos',
  'Blepandekager Danish Apple Pancakes',
  'Blond Minestrone',
  'Boat House Collard Greens',
  'Boo Tiful Jell O Cups',
  'Broccoli Casserole',
  'Brownies In The World Best Ever',
  'Buckley S Cajun Salmon Pasta',
  'Buffalo Stuffed Eggs',
  'Buffalo Wild Wings Medium Wing Sauce Copycat By Todd',
  'Buffalo Wing Mushrooms',
  'Burek Or Feta Cheese Phyllo Pie',
  'California Roll Salad',
  'Call The Fire Department Hot Wings',
  'Calm Your Nerves Tonic',
  'Can Spaghetti Sauce Oamc',
  'Can T Fail Holiday Fruitcake',
  'Cancer Curing Matzah Ball Soup',
  'Caramel Apples',
  'Casserole',
  'Cheeeezy Potatoes',
  'Cheese Sauce Dairy Free',
  'Cheeseburger Cookies And Fries',
  'Cheeseburger Meatloaf For Lactose Intolerant Cheese',
  'Cheeseburger Stuffed French Bread',
  'Cheesecake Factory Crab Cakes',
  'Cheesy Tuna Casserole',
  'Cheesy Vegan Lasagna',
  'Chef Salad Dressing',
  'Chic Greek Salad',
  'Chic To Be Greek Salad From Salad Creations',
  'Chicken Fried Fish Fingers',
  'Chicken Lickin Good Pork Chops',
  'Chile Rellenos',
  'Chili For The Crockpot',
  'Chinese Chop Suey',
  'Chinese Popcorn',
  'Chipotle Style Chicken Burrito Bowls',
  'Chmeur S Pudding',
  'Chocolate Cake',
  'Chocolate Chip Cookies',
  'Chocolate Chip Cookies Recipe',
  'Cloud Nine',
  'Coal Miners Gnocchi',
  'Comfort Able Kamikaze',
  'Company Green Beans',
  'Company S Coming Rice',
  'Country Fried Pig Fingers',
  'Country Style Onion Soup',
  'Crab Noodle Bowl',
  'Crabby Bread',
  'Crabby Cracker Spread',
  'Crack Lasagna',
  'Crazy Easy Lo Mein',
  'Cream Of Cauliflower Soup Vegan',
  'Cream Of Chicken Soup',
  'Cream Of Mushroom Soup',
  'Cream Of Pumpkin Or Squash Soup Vegan',
  'Cream Of Spinach Soup',
  'Cream Of Spinach Soup Vegan',
  'Cream Of Whatever Soup',
  'Creamed Spinach',
  'Creamsicle Smoothie',
  'Creamy Broccoli Soup',
  'Creamy Chicken Curry',
  'Creamy Fiddlehead Soup',
  'Creamy Mushroom Soup',
  'Creamy Vegan Potato Leek Soup',
  'Crispy Crunchy Chicken',
  'Da Best Chicago Style Italian Beef',
  'Deep Fried Dessert Thingys',
  'Denauseating With Ginger Tea',
  'Der Wiener Schnitzel Style Chili Dog Sauce',
  'Diamond Creme Brulee',
  'Dipstir Crock Pot Dip',
  'Dirty Broccoli',
  'Don T Bother With The Canned Stuff Sloppy Joes',
  'Don T Knock It Until You Try It Beet Cake',
  'Dorito Popcorn Seasoning',
  'Dressed Up Greek Style Salad',
  'Dressed Up Salad With Secret Dressing',
  'Drunken Pork Chops',
  'Duffins Donut Muffins',
  'Easiest Ever Hollandaise Sauce',
  'Egg Cellent Noodles',
  'Elephant Ear Dutch Baby',
  'Elmer S Summertime Sweet Onion Salsa',
  'Emerald Ecstasy Green Smoothie',
  'Emotional Balance Spice Mixture',
  'Even I Like These Bran Muffins',
  'Evil Chicken',
  'Exotic Fruits Barbecue Marinade',
  'Extraordinary Macaroni And Cheese',
  'Fabulous Brownies',
  'Fake Blueberry Cheesecake',
  'Fall Ing For Spice Cake',
  'Famous Garlic Noodles',
  'Faux Sourdough',
  'Favorite Chinese Steamed Whole Fish By Sy',
  'Fire Sauce',
  'First Skillet Cornbread',
  'Fish Herb Crust',
  'Flaky Oatmeal Raisin Cookies',
  'Flipped Roast Turkey',
  'Foodies Succotash',
  'Fool The Meat Eaters Chili',
  'Fooled Me Flourless Peanut Butter Cookies',
  'Forgotten Minestrone',
  'Fraicheur Vinaigrette',
  'Free Toe Pie',
  'French Onion Soup',
  'Fried Cauliflower',
  'Fried Pork Chops And Gravy',
  'From The Field Balsamic Vinaigrette',
  'From The Field Green Beans Fresh Herbs And Walnuts',
  'Fronch Toast',
  'Full Cool Macaroni And Cheese',
  'Funny Bones Cake',
  'Geebee Special Sandwiches',
  'George S At The Cove Black Bean Soup',
  'German Barbecued Carrots',
  'Get The Sensation Brownies',
  'Gilded Zucchini',
  'Gimme A Cheap Weeknight Dinner Quick',
  'Glazed Meatloaf',
  'Global Gourmet Taco Casserole',
  'Go Bears Party Ryes',
  'Go To Bbq Sauce For Ribs',
  'Gobble Up Turkey Cottage Pie',
  'Golden Circle Pineapple Upside Down Cake',
  'Good Morning Muffins',
  'Goulash Heart Healthy Version',
  'Goulashy Beef Stew For The Slow Cooker',
  'Granny Squash Creamed Squash',
  'Green Eggs Kid Friendly High In Iron',
  'Green Soup',
  'Greens To Go Smoothie',
  'Grey Cup Sourdough',
  'Grilled Venison Burgers',
  'Guilt Free Ice Cream Wannabe',
  'Ham Solo Savory Cake',
  'Hamburger Buns Zero Carb',
  'Harak Mas Curry Sri Lankan Beef Curry',
  'Hawaiian Chicken Salad Appetizer',
  'He Proposed Red Velvet Cake',
  'Healthified Decadent Hot Chocolate',
  'Healthy Fried Rice',
  'Healthy Minute Mug Cake',
  'Healthy Pumpkin Pie',
  'Hershey S Special Dark Chocolate Chip Cookies',
  'Hershey S Triple Layer Cheesecake',
  'Hey Nic Add The Chicken Leek And Potato Soup',
  'Hibachi Style Salad Dressing',
  'Hindu Spaghetti Casserole',
  'Homemade Hamburger Helper',
  'Homemade Vegetable Soup From A Can',
  'Honey I M Peanuts About You Cake',
  'Hot Tamale Burgers',
  'How I Got My Family To Eat Spinach Spinach Casserole',
  'Human Puppy Chow',
  'I Am Tired Of Living Cocktail',
  'I Can T Believe I Made Cream Puffs',
  'I Can T Believe It Is Butter Margarine Spread',
  'I Can T Believe It S Low Fat Creamy Potato Salad',
  'I Can T Believe It S Spinach',
  'I Coulda Had A Stuffed Pepper Stuffed Peppers',
  'I Don T Believe It S Lemon Tofu Cheesecake',
  'I Don T Feel Like Cooking Tonight Casserole',
  'I Don T Have Any Tahini Hummus',
  'I Fooled The Carnivores Vegan Barbecue',
  'I Hate Miracle Whip But I Love This Potato Salad That S',
  'I Stole The Idea From Mirj Sesame Noodles',
  'I Thought I Had Nothing To Eat Rice',
  'I Ve Only Got A Quarter Meal',
  'I Yam What I Yam Muffins',
  'I Yam What I Yam Two Muffins',
  'Icing',
  'If You Like Pina Coladas Protein Smoothie',
  'Immoral Sandwich Filling Loose Meat',
  'Impossible Bisquick Spinach Feta Pie',
  'In Canada Chocolate Chip Cookies',
  'In The Pink Lemonade',
  'Indian Macaroni And Cheese',
  'It S A Keeper Fish Stick Casserole',
  'It S Greek To Me Baked Feta Chicken',
  'It S Not A Secret Brisket',
  'It S That Easy Graham Cracker Delight',
  'It S Too Easy Pork Chops Rice Casserole',
  'It Smells Like Christmas Pumpkin Bread',
  'It Still Feels Like Winter Vegan Oatmeal Muffins',
  'Italian Fries',
  'Italian Gut Busters',
  'Italian Ized Pork Chops',
  'Italian Sandwich Pasta Salad',
  'Jamaican Me Hungry Chicken Bake',
  'Jamba Juice At Home Lime It Up Smoothie',
  'Jamba Juice At Home Strawberries Wild Smoothie',
  'Janie Marzetti',
  'Jeanne S Style Birthday Cake',
  'Jeera On Cubes Barbecue Marinade',
  'Jiffy Deluxe Pizza Sticks',
  'Jiffy Extra Moist Carrot Cake',
  'Jiffy Roasted Corn And Jalapeno Cornbread',
  'Joe S Peppermint Cookies N Cream Brownies',
  'Johnny Depp In A Bundt Pan A K A Black Russian Cake',
  'Just Peachy Cobbler',
  'Just Trust Me Bistro Chicken Salad',
  'Keep It Going German Friendship Cake',
  'Kelly S Chinese Cabbage Salad',
  'Kelly S Creamy Cheddar Pea Salad',
  'Kicked Up Baked Corn Pudding Casserole',
  'Kicked Up Macaroni And Cheese',
  'Kicked Up Oven Baked Pork Baby Back Ribs',
  'Kicked Up Oven Fried Chicken',
  'Killer Lasagna',
  'Kitchen Sink Chocolate Chunk Cookies',
  'Kitchen Sink Egg Bake',
  'Kitchen Sink Soup',
  'Korney Spinach Dip Stuffing Side Dish',
  'Lamb Chops Sensory Explosion',
  'Land Of Nod Cinnamon Buns',
  'Leave Me For You Chili',
  'Leftover Lo Mein For Two',
  'Leftover Roast Mexican Casserole',
  'Leftovers Dessert',
  'Leftovers Spaghetti Sauce',
  'Lemon Coconut Custard Pie',
  'Light Chocolate Chip Oatmeal Cookies',
  'Lighter Chocolate Peanut Butter Pie',
  'Lighter Pistachio Pudding Salad',
  'Like Money For Nuthin Fudge',
  'Lite Cretons',
  'Lite Tortillas',
  'Little Bear S Seafood Soup',
  'Little Kick Jalapeno Burgers',
  'Loaded Deviled Eggs',
  'Loco Moco Style Hamburger Steak With Gravy',
  'Love Is In The Air Beef Fondue Sauces',
  'Lplermagrone',
  'Lplermagrone Herdsman S Macaroni',
  'Lplermagronen',
  'Lupo S Chicken Spiedies',
  'Ma S Oatmeal Cake And Icing',
  'Magic Chicken Noodle Soup',
  'Magic Coleslaw',
  'Magic Cookie Bars',
  'Make It Your Way Shortcakes',
  'Make That Chicken Dance Salsa Pasta',
  'Mama Mia Triple Cheese Mostaccioli Bake',
  'Mamma Mia Ravioli Bites',
  'Mandarin Chicken',
  'Marco Polenta',
  'Margarita Bread',
  'Margarita Dip',
  'Margarita Dip For Fresh Or Grilled Fruit',
  'Martini',
  'Mcgriddle Pancakes Breakfast Sandwich',
  'Meal In A Bowl Guacamole Salad',
  'Meat Potatoes Meatloaf',
  'Meat Ralf Makeover',
  'Meatloaf',
  'Melanie S Chicken Chili',
  'Mennonite Corn Fritters',
  'Mexican Pasta',
  'Middle Eastern Twice Baked Potatoes',
  'Millionaire Pound Cake',
  'Minute Bread Pizza',
  'Missy S Sweet Potato Casserole',
  'Mock A Mole Low Fat Guacamole',
  'Mohnstrietzel German Poppy Seed Cake',
  'Mom S Amazing Banana Bread',
  'Mom S Chicken',
  'Momma S Special Marinade',
  'Moose Milk',
  'More Lish Ous Cornbread',
  'More More Apple Pear Jigglers',
  'Mostly Clean Eating Granola Bars',
  'Mr Grant You Took Half Veal Prince Orloff',
  'Muffalata Sandwich By Any Name Tastes Great',
  'Munch Without Guilt Tomatoes',
  'My Muffuletta Sandwich',
  'Nachos Casserole',
  'Naked Grilled Salmon',
  'Nat S King Cole Coleslaw',
  'Navajo Style Peach Crisp Vegan Friendly',
  'Near East Rice Pilaf Low Fat',
  'Need A Pick Me Up Banana Peanut Butter Smoothie No',
  'Never Weep Whipped Cream',
  'New Mashed Potatoes',
  'Next To Sex Dessert',
  'No Bake Cookie Crumble Cheesecake',
  'No Copycats Here Homemade Chicken Tortilla Soup',
  'No Egg Tomato Soup Cake',
  'No Fettuccine Spaghetti Alfredo',
  'No Fuss Easy Baked Artichokes',
  'No Harm Eggplant Parm Ww',
  'No More Fears Paella',
  'No Name Beef Recipe Loco Moco',
  'No Sausage Gravy For Biscuits And Gravy',
  'No Time Flat Nuked Nachos With Salsa And Cheese',
  'Not Lasagna',
  'Not Too Sweet Sweet Potatoes',
  'Not Your Average Ham Bean Soup',
  'Not Your Average Spuds',
  'Not Your Every Day Chicken Salad Chicken Salad',
  'Now And Later Vegetarian Empanadas',
  'Off The Boat Sicilian Pasta Sauce',
  'Off The Cob Freezer Corn',
  'Oh Boy Waffles',
  'Oh I Love This Cheesecake',
  'Old Bay Grilled Steak Fries',
  'Old Ladies On A Bus Chicken',
  'Old Reliable French Bread For Kitchen Aid Mixers',
  'Olive Garden Salad And Dressing Recipe',
  'One Bowl Perfect Pound Cake',
  'One Of Cookies No Bake Ingredients',
  'One Pot Brownies',
  'One Pot Dinner',
  'Oopah Feta Chicken Breasts',
  'Oops There It Is Chocolate Cake Low Fat',
  'Open Sesame Noodles',
  'Orange Soup',
  'Outback Steak Rub',
  'Pancakes In A Bowl',
  'Pantry Raid Chicken Enchilada Casserole',
  'Party Taco Dip',
  'Pass Me Another Hot Clam Dip',
  'Pasta With Shrimp Eggplant',
  'Payday Candy Bar Squares',
  'Peanut Butter Jam Sandwich Muffins',
  'Peas Fit For A King Or Queen',
  'Perfect Chocolate Cake Mccall S Cooking School',
  'Perfect Chocolate Frosting',
  'Philly Guacamole Dip',
  'Philly Roll Sushi',
  'Philly Waldorf Salad',
  'Pick Me Up Party Chicken Kabobs',
  'Pinards En Branche Sauted Spinach',
  'Pink Stuff',
  'Pink Stuff Cherry Pie Filling Pineapple Dessert',
  'Pita The Great Tuna Salad',
  'Pizza Beans',
  'Pizza Pan Potato Skins',
  'Pizza Steak',
  'Pizza Stuffed Potato',
  'Please Make Those Meatballs Crockpot Meatballs',
  'Posh Pork Roast Crockpot',
  'Pour Over Anything Mushroom Gravy',
  'Prize Winning Chili Con Carne',
  'Puddingkuchen Custard Bake',
  'Puerto Rican Style Fried Rice',
  'Pumpkin Pie',
  'Pumpkin Pie Filling For Mexico',
  'Put Down Your Fork Tuna And Bean Salad',
  'Quick And Healthy Picker Uppers Apple Treats',
  'Quick Biscuit Bread',
  'Quick Buns',
  'Radler Mass German Beer Cooler',
  'Rainbow Chicken Strips',
  'Rathu Isso Curry Sri Lankan Red Prawn Curry',
  'Real Italian Bolognese Sauce',
  'Real New York Style Cheesecake Supreme',
  'Real Strawberry Pie With French Cream Topping',
  'Reasonable Lemon Chicken And Potatoes',
  'Red Hot Applesauce',
  'Red Macaroni Salad',
  'Red River Shoot Out Pigskins',
  'Red Robin Drink Recipe Mai Tai',
  'Rich Hot Fudge Cake',
  'Rise And Shine German Fruit Pancake',
  'Ritz Y Chicken',
  'Roast Pork And Apple Dinner',
  'Royal Turkey Stuffing',
  'Rter Med Flsk Pea Soup With Pork',
  'Rtsoppa Swedish Yellow Pea Soup',
  'Russian Dressing Ww',
  'S Wonderful Carrot And Raisin Salad',
  'Sangria Fruit Cups Non Alcoholic',
  'Sannich In Soup',
  'Sara Lee Pound Cake Copycat',
  'Sausage And Gravy Low Fat',
  'Second Only To My Meatloaf Meatballs',
  'Secret Ingredient Bbq Meatloaf',
  'Secret Ingredient Beef Stew',
  'Seva Bean Vegetable Stew',
  'Sexy Greek Cocktail',
  'Sexy Sauce',
  'She Crab Cream Of Crab Soup',
  'Sherried Mushroom Sauce',
  'Skinny Meatloaf',
  'Skordy New Potatoes W Rosemary Lemon Olive Oi',
  'Slightly Spicy Black Bean Burgers',
  'Sloughed Tortellini Salad',
  'Smells Like Sunday Chicken Fricassee With Meatballs',
  'Smoked Salmon Cracker Spread',
  'Some Like It Hot',
  'Souper Easy Sweet Sour Meatballs',
  'Sour Cream Avocado Dip Vegan',
  'South Beach Stuffed Bell Peppers',
  'Spicy Banana Bread',
  'Splenda D Cheesecake Sugar Free Low Carb',
  'Squash Dressing',
  'Steamed Chicken Cutlets In Packages',
  'Sticky Chicky Dump Chicken',
  'Stove Top Bbq Beef Or Pork Ribs',
  'Stove Top Stuffing',
  'Sun Dried Tomatoes',
  'Symphony Brownies',
  'Tacos',
  'Tangy Chicken Recipe',
  'Tastes Like Mounds Bar Kahlua Cake',
  'The Best Banana Bread Or Muffins',
  'The Best Chocolate Chip Cheesecake Ever',
  'The Bomb Pumpkin Soup',
  'The Carrot Cake',
  'The Creamed Dried Beef Chipped Beef Recipe',
  'The Elvis Smoothie',
  'The Man S Taco Dip',
  'The Mooch Zucchini Sandwich',
  'The U Of L Game Day Dip',
  'The Woiks Dilly Burgers',
  'The Works Crock Pot Chili',
  'Thicker Than Pea Soup Pea Soup',
  'Things Hot Mexican Green Chile Dip',
  'This Old House Dressing',
  'Tide Me Over Indian Chaat Simple Veggie Salad',
  'To Your Health Muffins',
  'Trini Burgers',
  'Truth Serum Margaritas',
  'Turtle Squares',
  'Twisted American Chop Suey',
  'Voodoo Calamari Ink Pasta',
  'Wacky Cake',
  'Wait Forever Pork Chops',
  'We Hate Zucchini Bread Zucchini Bread',
  'We Thought It Was A Layer Cake Sandwich',
  'White Sangria',
  'Wild Game Moose Sloppy Joes',
  'Windy S Sweet And Sour Meatballs',
  'You Bring The Macaroni Salad Macaroni Salad',
  'You Can T Eat Just One Ice Box Cookies',
  'Yummy N Easiest Warm Blueberry Sauce',
  'Zucchini Mix In Tomato Sauce',
  'Zupa Ze Swiezych Grzybow Polish Mushroom Soup',
];
